---
catalyst_center_hosts:
  hosts:
    catalyst_center220:
      #(Mandatory) CatC IP address from environment variable HOSTIP
      catalyst_center_host: "{{ lookup('ansible.builtin.env', 'HOSTIP') }}"
      #(Mandatory) CatC UI admin password from environment variable CATALYST_CENTER_PASSWORD
      catalyst_center_password: "{{ lookup('ansible.builtin.env', 'CATALYST_CENTER_PASSWORD') }}"
      catalyst_center_port: 443
      catalyst_center_timeout: 60
      #(Mandatory) CatC UI admin username from environment variable CATALYST_CENTER_USERNAME
      catalyst_center_username: "{{ lookup('ansible.builtin.env', 'CATALYST_CENTER_USERNAME') }}"
      catalyst_center_verify: false
      #(Mandatory) DNAC Release version
      catalyst_center_version: 2.3.7.9
      catalyst_center_debug: true
      catalyst_center_log_level: INFO
      catalyst_center_log: true
      #(Optional override) ANSIBLE_PYTHON_INTERPRETER; otherwise use current ansible-playbook Python
      ansible_python_interpreter: "{{ lookup('ansible.builtin.env', 'ANSIBLE_PYTHON_INTERPRETER') | default(ansible_playbook_python, true) }}"
      #Device migration configuration
      port_assignment_migration:
      - fabric_site: "Global/California/23"
        source_device_ip: "10.195.120.173"
        destination_device_ip: "10.195.120.219"
