---
- name: Assurance health score playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Example task
      debug:
        msg: "This is a placeholder for the assurance_health_score_playbook playbook."
