---
network_device:
  add:
    - ip_address_list:
        - 10.4.213.6
        - 10.4.213.5
      ipv6Enabled: false
      type: NETWORK_DEVICE
      cli_transport: ssh
      username: xxxx
      password: xxxx
      enable_password: xxxx
      snmp_version: v3
      snmp_username: xxxx
      snmp_mode: AUTHPRIV
      snmp_auth_protocol: SHA
      snmp_auth_passphrase: xxxx
      snmp_priv_protocol: AES128
      snmp_priv_passphrase: xxxx
      snmp_retry: 3
      snmp_timeout: 5
      netconf_port: 830
      device_added: true

  provision:
    - provision_wired_device:
        - device_ip: 10.4.213.6
          site_name: Global/USA/SAN-FRANCISCO/SF_BLD2
        - device_ip: 10.4.213.5
          site_name: Global/USA/SAN JOSE/SJ_BLD22

  reprovision:
    - reprovision_wired_device:
        - device_ip: 10.4.213.6
          site_name: Global/USA/SAN-FRANCISCO/SF_BLD2
        - device_ip: 10.4.213.5
          site_name: Global/USA/SAN JOSE/SJ_BLD22

wireless_network_device:
  add:
    - ip_address_list:
        - 10.4.218.250
      ipv6Enabled: false
      type: NETWORK_DEVICE
      cli_transport: ssh
      username: xxxx
      password: xxxx
      enable_password: xxxx
      snmp_version: v3
      snmp_username: xxxx
      snmp_mode: AUTHPRIV
      snmp_auth_protocol: SHA
      snmp_auth_passphrase: xxxx
      snmp_priv_protocol: AES128
      snmp_priv_passphrase: xxxx
      snmp_retry: 3
      snmp_timeout: 5
      netconf_port: 830
      device_added: true

  provision:
    - provision_wireless_device:
        - device_ip: 10.4.218.250
          site_name: Global/USA/SAN-FRANCISCO/SF_BLD2
          managed_ap_locations:
            - Global/USA/SAN-FRANCISCO/SF_BLD2/FLOOR1
            - Global/USA/SAN-FRANCISCO/SF_BLD2/FLOOR2
            - Global/USA/SAN-FRANCISCO/SF_BLD2/FLOOR3
          dynamic_interfaces:
            - interface_ip_address: 10.4.218.250
              interface_netmask_in_cidr: 28
              interface_gateway: 10.4.218.241
              vlan_id: 2015
              interface_name: TenGigabitEthernet0/0/0
