---
- name: This playbook manages operations on SDA fabric devices, including adding and updating fabric devices on Cisco Catalyst Center.
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
  - "{{ VARS_FILE_PATH }}"

  vars:
    state: merged
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_port: "{{ dnac_port }}"
      dnac_verify: "{{ dnac_verify }}"
      config_verify: "{{ catalyst_center_config_verify | default(False) }}"
      dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
      dnac_debug: "{{ catalyst_center_debug | default(dnac_debug) }}"
      dnac_log: "{{ catalyst_center_log | default(dnac_log) }}"
      dnac_log_level: "{{ catalyst_center_log_level | default(dnac_log_level) }}"
      dnac_log_file_path: "{{ catalyst_center_log_file_path | default(dnac_log_file_path) }}"
      dnac_log_append: "{{ catalyst_center_log_append | default(dnac_log_append) }}"
  tasks:
    - name: Include the variables file {{ VARS_FILE_PATH }} for the playbook
      include_vars:
        file: "{{ VARS_FILE_PATH }}"
      when: VARS_FILE_PATH is defined
    - set_fact:
        dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
    - debug:
        msg: "Catalyst Center version: {{ dnac_version }}"

    - name: SDA Fabric Device Playbook start time
      set_fact:
        long_op_start: "{{ now() }}"
      
    - name: SDA Fabric Device Playbook start
      cisco.dnac.sda_fabric_devices_workflow_manager:
        <<: *dnac_login
        state: "{{ state }}"
        config: "{{ fabric_devices_details }}"
      register: sda_fabric_output
      when: fabric_devices_details is defined

    - name: Print SDA Fabric Devices Output
      debug:
        msg: "{{ sda_fabric_output }}"
      when: sda_fabric_output is defined

    - name: Playbook end time
      set_fact:
        long_op_end: "{{ now() }}"
      
    - name: Display Playbook Execution Time
      debug:
        msg: "SDA Fabric Device Role playbook runtime: Start {{ long_op_start }}, End {{ long_op_end }}"

  post_tasks:
    - name: Verify Python version on Catalyst Center host
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local

