---
- name: Playbook to manage Cisco Catalyst Center Device Inventory
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILE_PATH }}"
  vars:
    state: merged
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_port: "{{ dnac_port }}"
      dnac_verify: "{{ dnac_verify }}"
      config_verify: "{{ catalyst_center_config_verify | default(False) }}"
      dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
      dnac_debug: "{{ catalyst_center_debug | default(dnac_debug) }}"
      dnac_log: "{{ catalyst_center_log | default(dnac_log) }}"
      dnac_log_level: "{{ catalyst_center_log_level | default(dnac_log_level) }}"
      dnac_log_file_path: "{{ catalyst_center_log_file_path | default(dnac_log_file_path) }}"
      dnac_log_append: "{{ catalyst_center_log_append | default(dnac_log_append) }}"
  tasks:
    - name: print VARS_FILE_PATH
      debug:
        msg: "Input file selected {{ VARS_FILE_PATH }}"
    - name: Playbook start time for the inventory playbook
      set_fact:
        long_op_start: "{{ now() }}"
    - name: Add/Update/assig to site/Provision in file "{{ VARS_FILE_PATH }}" and state "{{ state }}"
      cisco.dnac.inventory_workflow_manager:
        <<: *dnac_login
        state: "{{ state }}"
        config: "{{ inventory_details.network_devices }}" 
      register: inventory_output
      when: inventory_details.network_devices is defined
    - name: Print the Inventory devices output
      debug:
        msg: "{{inventory_output}}"
    - name: Playbook end time for the inventory playbook
      set_fact:
        long_op_end: "{{ now() }}"
    - name: Print Inventory devices playbook execution time
      debug:
        msg: "Inventory devices playbook run time: {{ long_op_start }}, end: {{ long_op_end }}"
  post_tasks:
    - name: run command module to find python version
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local
  

