---
- name: This playbook manages creating and updating the templates projects and templates on Cisco Catalyst Center
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars:
    state: merged
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
      dnac_debug: "{{ dnac_debug }}"
      dnac_log_level: "{{dnac_log_level}}"
      dnac_log: "{{dnac_log}}"
  tasks:
    - name: Include the variables file {{ VARS_FILE_PATH }} for the playbook
      include_vars:
        file: "{{ VARS_FILE_PATH }}"
      when: VARS_FILE_PATH is defined
    - set_fact:
        dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
    - debug:
        msg: "Catalyst Center version: {{ dnac_version }}"

    - name: Templates Playbook start time
      set_fact:
        long_op_start: "{{ now() }}"
    - name: Templates Playbook start time
      #Import an image from a URL
      cisco.dnac.template_workflow_manager:
        <<: *dnac_login
        state: "{{ state }}"
        config: "{{ template_details }}"
      register: template_output
      when: template_details is defined
    - name: Print the Templates output
      debug:
        msg: "{{template_output}}"
      when: template_output is defined

    - name: Templates playbook end time
      set_fact:
        long_op_end: "{{ now() }}"

    - name: Print Templates Playbook execution time
      debug:
        msg: "Templates playbook run time: {{ long_op_start }}, end: {{ long_op_end }}"
  post_tasks:
    - name: run command module to find python version
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local