---
- name: Configure device credentials on Cisco DNA Center
  hosts: dnachosts
  connection: local
  gather_facts: no
  vars_files:
    - "{{ VARS_FILES_PATH }}"
  
  vars:
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
  
  tasks:
    - name: Upload the images to Cisco DNA Center
      cisco.dnac.swim_intent:
        <<: *dnac_login
        config:
        - "{{ item }}"
      loop: "{{ image_details }}"
      when: image_details is defined
      register: image_details_result
    - debug:
        msg: "{{ image_details_result }}"

    - name: Golden tag uploaded images
      cisco.dnac.swim_intent:
        <<: *dnac_login
        config:
        - "{{ item }}"
      loop: "{{ image_golden_tagging_details }}"
      when: image_golden_tagging_details is defined
      register: image_golden_tagging_details_result
    - debug:
        msg: "{{ image_golden_tagging_details_result }}"
