---
- name: Configure device credentials on Cisco DNA Center
  hosts: dnachosts
  connection: local
  gather_facts: no
  vars_files:
    - "{{ VARS_FILES_PATH }}"
  
  vars:
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"

  tasks:
    - name: Set all_network_devices required by the filter
      set_fact:
        all_network_devices:  "{{ network_devices }}"
      when: network_devices is defined
    - name: Set filters_object required by the filter
      set_fact:
        filters_object:  "{{ imageDistributionDetails}}"
    - import_tasks: ../common_tasks/filter_device_serial_numbers_for_role_site.yml

    - name: Distribute image to selected devices
      cisco.dnac.swim_intent:
        <<: *dnac_login
        config:
        - imageDistributionDetails:
            deviceSerialNumber: "{{ item }}"
            imageName: "{{ imageDistributionDetails.imageName }}"
      loop: "{{ filtered_devices_list }}"
      when: imageDistributionDetails is defined and filtered_devices_list is defined
      register: imageDistributionDetails_result

    - name: Distribute image to selected devices if IP address is defined
      cisco.dnac.swim_intent:
        <<: *dnac_login
        config:
        - imageDistributionDetails:
            deviceIPAddress: "{{ imageDistributionDetails.deviceIPAddress }}"
            imageName: "{{ imageDistributionDetails.imageName }}"
      when: 
        - imageDistributionDetails is defined 
        - imageDistributionDetails.deviceIPAddress is defined 
        - imageDistributionDetails.deviceIPAddress != none
        - filtered_devices_list is not defined

    - name: Distribute image to selected devices if hostname is defined
      cisco.dnac.swim_intent:
        <<: *dnac_login
        config:
        - imageDistributionDetails:
            deviceHostname: "{{ imageDistributionDetails.deviceHostname }}"
            imageName: "{{ imageDistributionDetails.imageName }}"
      when: 
        - imageDistributionDetails is defined 
        - imageDistributionDetails.deviceHostname is defined 
        - imageDistributionDetails.deviceHostname != none
        - filtered_devices_list is not defined

    - name: DIstribute image to selected devices if deviceMacAddress is defined
      cisco.dnac.swim_intent:
        <<: *dnac_login
        config:
        - imageDistributionDetails:
            deviceMacAddress: "{{ imageDistributionDetails.deviceMacAddress }}"
            imageName: "{{ imageDistributionDetails.imageName }}"
      when: 
        - imageDistributionDetails is defined 
        - imageDistributionDetails.deviceMacAddress is defined
        - imageDistributionDetails.deviceMacAddress != none
        - filtered_devices_list is not defined

    - name: DIstribute image to selected devices if deviceSerialNumber is defined
      cisco.dnac.swim_intent:
        <<: *dnac_login
        config:
        - imageDistributionDetails:
            deviceSerialNumber: "{{ imageDistributionDetails.deviceSerialNumber }}"
            imageName: "{{ imageDistributionDetails.imageName }}"
      when: 
        - imageDistributionDetails is defined
        - imageDistributionDetails.deviceSerialNumber is defined
        - imageDistributionDetails.deviceSerialNumber != none
        - filtered_devices_list is not defined