---
- name: Playbook to manage Cisco Catalyst Center Plug and Play, add pnp devices, bulk import, delete, update, claim routing, switching devices and wirelesss controllers. 
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILE_PATH }}"
  vars:
    state: merged
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
      dnac_log: "{{ dnac_log }}"
      dnac_log_level: "{{ dnac_log_level }}"

  tasks:
    - name: Add/Update/assig to site/Provision or delete devices provided in file "{{ VARS_FILE_PATH }}" and state "{{ state }}"
      cisco.dnac.pnp_workflow_manager::
        <<: *dnac_login
        state: "{{ state }}"
        config:
          - "{{ item }}"
      loop: "{{ pnp_details.add_network_devices }}"
      when: pnp_details.add_network_devices is defined

    - name: Claim Wireless Controller 98XX EWLC devices through PnP
      cisco.dnac.pnp_workflow_manager::
        <<: *dnac_login
        state: merged
        config:
        - "{{ item }}"
      loop: "{{ pnp_details.claim_ewlc_devices }}"
      when: pnp_details.claim_ewlc_devices is defined

    - name: Claim Routing devices through PnP
      cisco.dnac.pnp_workflow_manager::
        <<: *dnac_login
        state: merged
        config:
        - "{{ item }}"
      loop: "{{ pnp_details.claim_router_devices }}"
      when: pnp_details.claim_router_devices is defined

    - name: Claim Switching devices through PnP
      cisco.dnac.pnp_workflow_manager::
        <<: *dnac_login
        state: merged
        config:
        - "{{ item }}"
      loop: "{{ pnp_details.claim_switching_devices }}"
      when: pnp_details.claim_switching_devices is defined

    - name: Claim Access Point devices through PnP
      cisco.dnac.pnp_workflow_manager::
        <<: *dnac_login
        state: merged
        config:
        - "{{ item }}"
      loop: "{{ pnp_details.claim_ap_devices }}"
      when: pnp_details.claim_ap_devices is defined