---
- name: Playbook to manage Cisco Catalyst Center Plug and Play, add pnp devices, bulk import, update, claim routing, switching devices and wirelesss controllers. 
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILE_PATH }}"
  vars:
    state: deleted
    catalyst_center_login: &catalyst_center_login
      dnac_host: "{{ catalyst_center_host | default(dnac_host) }}"
      dnac_username: "{{ catalyst_center_username | default(dnac_username) }}"
      dnac_password: "{{ catalyst_center_password | default(dnac_password) }}"
      dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
      dnac_port: "{{ catalyst_center_port | default(443) }}"
      dnac_verify: "{{ catalyst_center_verify | default(dnac_verify) }}"
      config_verify: "{{ catalyst_center_config_verify | default(False) }}"
      dnac_debug: "{{ catalyst_center_debug | default(False) }}"
      dnac_log: "{{ catalyst_center_log | default(False) }}"
      dnac_log_level: "{{ catalyst_center_log_level | default('INFO') }}"
      dnac_log_file_path: "{{ catalyst_center_log_file_path |  default(omit) }}"
      dnac_log_append: "{{ catalyst_center_log_append |  default(False) }}"
      dnac_api_task_timeout: "{{ catalyst_center_api_task_timeout |  default(1200) }}"
      
  tasks:
    - name: Network Plug and Play devices on Cisco Catalyst Center
      set_fact:
        long_op_start: "{{ now() }}"

    # Remove pnp devices on Cisco Catalyst Center
    - name: Remove pnp devices to Cisco Catalyst Center
      cisco.dnac.pnp_workflow_manager:
        <<: *catalyst_center_login
        state: "{{ state }}"
        config: "{{ pnp_details.network_devices }}"
      register: network_devices_output
      when: pnp_details.network_devices is defined
    - name: Print the network devices output
      debug:
        msg: "{{network_devices_output}}"
      when: network_devices_output is defined

    # Remove Routing devices through PnP 
    - name: Remove Routing devices through PnP
      cisco.dnac.pnp_workflow_manager:
        <<: *catalyst_center_login
        state: "{{ state }}"
        config: "{{ pnp_details.claim_router_devices }}"
      register: router_devices_output
      when: pnp_details.claim_router_devices is defined
    - name: Print the router devices output
      debug:
        msg: "{{router_devices_output}}"
      when: router_devices_output is defined

    # Remove Switching devices through PnP
    - name: Remove Switching devices through PnP
      cisco.dnac.pnp_workflow_manager:
        <<: *catalyst_center_login
        state: "{{ state }}"
        config: "{{ pnp_details.claim_switching_devices }}"
      register: switching_devices_output
      when: pnp_details.claim_switching_devices is defined
    - name: Print the switching devices output
      debug:
        msg: "{{switching_devices_output}}"
      when: switching_devices_output is defined

    # Remove Wireless Controller EWLC devices through PnP
    - name: Remove Wireless Controller EWLC devices through PnP
      cisco.dnac.pnp_workflow_manager:
        <<: *catalyst_center_login
        state: "{{ state }}"
        config: "{{ pnp_details.claim_wireless_controllers }}"
      register: wireless_controllers_output
      when: pnp_details.claim_wireless_controllers is defined
    - name: Print the wireless controllers output
      debug:
        msg: "{{wireless_controllers_output}}"
      when: wireless_controllers_output is defined
    # Remove Access Point device through PnP
    - name: Remove Point device through PnP
      cisco.dnac.pnp_workflow_manager:
        <<: *catalyst_center_login
        state: "{{ state }}"
        config: "{{ pnp_details.claim_access_points }}"
      register: access_points_output
      when: pnp_details.claim_access_points is defined
    - name: Print the access points output
      debug:
        msg: "{{access_points_output}}"
      when: access_points_output is defined

    - name: Network Plug and Play devices playbook end time
      set_fact:
        long_op_end: "{{ now() }}"
    - name: Print Network Plug and Play devices playbook execution time
      debug:
        msg: "Network Plug and Play devices playbook run time: {{ long_op_start }}, end: {{ long_op_end }}"
