catalyst_center_version: 2.3.7.9
catalyst_center_verify: false
assurance_health_score_settings:
  - device_health_score:
    - device_family: ROUTER
      kpi_name: Link Utilization
      include_for_overall_health: true
      threshold_value: 90
      synchronize_to_issue_threshold: false
    - device_family: ROUTER
      kpi_name: BGP Session from Border to Control Plane (BGP)
      include_for_overall_health: true
    - device_family: ROUTER
      kpi_name: BGP Session from Border to Control Plane (PubSub)
      include_for_overall_health: true