# Yamale validation schema for application_policy
# This schema is used to validate the input data for the application policy workflow
catalyst_center_version: str(required=False)
catalyst_center_verify: bool(required=False)
catalyst_center_api_task_timeout: int(required=False, default=1200)
catalyst_center_debug: bool(required=False, default=False)
catalyst_center_log: bool(required=False, default=False)
catalyst_center_log_append: bool(required=False, default=True)
catalyst_center_log_file_path: str(required=False, default='dnac.log')
catalyst_center_log_level: enum("CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG", required=False)
catalyst_center_config_verify: bool(required=False)
application_policy_details: list(include('application_policy_details_type'), required=True, min=0, max=500)

---
application_policy_details_type:
  queuing_profile: list(include('queuing_profile_type'), required=False)
  application_sets: list(include('application_sets_type'), required=False)
  application: list(include('application_type'), required=False)
  application_policy: list(include('application_policy_type'), required=False)

queuing_profile_type:
  profile_name: str(required=True)
  new_profile_name: str(required=False)
  profile_description: str(required=False)
  bandwidth_settings: include('bandwidth_settings_type', required=False)
  dscp_settings: list(include('dscp_settings_type'), required=False)

bandwidth_settings_type:
  is_common_between_all_interface_speeds: bool(required=False)
  interface_speed_bandwidth_clauses: list(include('interface_speed_bandwidth_clauses_type'), required=False)

interface_speed_bandwidth_clauses_type:
  interface_speed: enum("ALL", "HUNDRED_GBPS", "TEN_GBPS", "ONE_GBPS", "HUNDRED_MBPS", "TEN_MBPS", "ONE_MBPS", required=False)
  bandwidth_percentages: include('bandwidth_percentages_type', required=False)

bandwidth_percentages_type:
  transactional_data: str(required=False)
  best_effort: str(required=False)
  voip_telephony: str(required=False)
  multimedia_streaming: str(required=False)
  real_time_interactive: str(required=False)
  multimedia_conferencing: str(required=False)
  signaling: str(required=False)
  scavenger: str(required=False)
  ops_admin_mgmt: str(required=False)
  broadcast_video: str(required=False)
  network_control: str(required=False)
  bulk_data: str(required=False)

dscp_settings_type:
  transactional_data: str(required=False)
  best_effort: str(required=False)
  voip_telephony: str(required=False)
  multimedia_streaming: str(required=False)
  real_time_interactive: str(required=False)
  multimedia_conferencing: str(required=False)
  signaling: str(required=False)
  scavenger: str(required=False)
  ops_admin_mgmt: str(required=False)
  broadcast_video: str(required=False)
  network_control: str(required=False)
  bulk_data: str(required=False)

application_sets_type:
  name: str(required=True)

application_type:
  name: str(required=True)
  description: str(required=False)
  help_string: str(required=False)
  type: enum("server_name", "url", "server_ip", required=False)
  server_name: str(required=False)
  dscp: str(required=False)
  network_identity: list(include('network_identity_type'), required=False)
  app_protocol: enum("TCP", "UDP", "TCP_UDP", "IP", required=False)
  url: str(required=False)
  traffic_class: enum("BROADCAST_VIDEO", "BULK_DATA", "MULTIMEDIA_CONFERENCING", "MULTIMEDIA_STREAMING", "NETWORK_CONTROL", "OPS_ADMIN_MGMT", "REAL_TIME_INTERACTIVE", "SIGNALING", "TRANSACTIONAL_DATA", "VOIP_TELEPHONY", "BEST_EFFORT", "SCAVENGER", required=False)
  ignore_conflict: str(required=False)
  rank: str(required=False)
  engine_id: str(required=False)
  application_set_name: str(required=False)

network_identity_type:
  protocol: str(required=False)
  port: str(required=False)
  ip_subnet: list(str(), required=False)
  lower_port: str(required=False)
  upper_port: str(required=False)

application_policy_type:
  name: str(required=True)
  application_set_name: str(required=False)
  policy_details: enum("NONE", "DELETED", "RESTORED", required=False)
  site_names: list(str(), required=False)
  device_type: str(required=True)
  device: include('device_type_type', required=False)
  application_queuing_profile_name: str(required=False)
  clause: list(include('clause_details_type'), required=False)
  
device_type_type:
  device_ip: str(required=False)
  wlan_id: str(required=False)

clause_details_type:
  clause_type: enum("BUSINESS_RELEVANCE", "APPLICATION_POLICY_KNOBS", required=False)
  relevance_details: list(include('relevance_details_type'), required=False)

relevance_details_type:
  relevance: enum("BUSINESS_RELEVANT", "BUSINESS_IRRELEVANT", "DEFAULT", required=False)
  application_set_name: str(required=False)
#====================================================================
#   End of schema
#====================================================================
