---
- name:  Create wireless SSIDs, Enterprise SSIDs, and Guest SSIDs on Cisco Catalyst Center and assign them to the wireless Profiles and sites
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no
  vars_files:
    - "{{ VARS_FILE_PATH }}"
  vars:
    state: merged
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_port: "{{ dnac_port }}"
      dnac_verify: "{{ dnac_verify }}"
      config_verify: "{{ catalyst_center_config_verify | default(False) }}"
      dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
      dnac_debug: "{{ catalyst_center_debug | default(dnac_debug) }}"
      dnac_log: "{{ catalyst_center_log | default(dnac_log) }}"
      dnac_log_level: "{{ catalyst_center_log_level | default(dnac_log_level) }}"
      dnac_log_file_path: "{{ catalyst_center_log_file_path | default(dnac_log_file_path) }}"
      dnac_log_append: "{{ catalyst_center_log_append | default(dnac_log_append) }}"
  tasks:
    # Include the variables file {{ VARS_FILE_PATH }} for the playbook
    - name: Include the variables file {{ VARS_FILE_PATH }} for the playbook
      include_vars:
        file: "{{ VARS_FILE_PATH }}"
    # set the password file path
    - name: set the password file path
      set_fact:
        passwords_file: "{{ passwords_file  | default('../../../ansible_vault_encrypted_inputs/mypasswordfile.yaml') }}"
      when: jinjatemplate is defined and jinjatemplate is true 
    # load password file
    - name: load password file
      include_vars:
        file: "{{ passwords_file }}"
      when: jinjatemplate is defined and jinjatemplate is true and passwords_file is defined
    # Create inputs from the Jinja Template
    - name: Create inputs from the Jinja Template
      template: 
        src: "{{ jinjatemplate_file }}"
        dest: ../tmp/template_generated_file.yaml
      when:  jinjatemplate is defined and jinjatemplate is true and jinjatemplate_file is defined

    # Include the variables file {{ VARS_FILE_PATH }} for the playbook
    - name: Include the variables file {{ VARS_FILE_PATH }} for the playbook
      include_vars:
        file: ../tmp/template_generated_file.yaml
      when: jinjatemplate is defined
    # Include the variables file {{ VARS_FILE_PATH }} for the playbook
    - name: Include the variables file {{ VARS_FILE_PATH }} for the playbook
      include_vars:
        file: "{{ VARS_FILE_PATH }}"
      when: jinjatemplate is not defined or jinjatemplate is false
    - name: Start time for the playbook
      set_fact:
        long_op_start: "{{ now() }}"
    - name: Create the given roles and users on Cisco Catalyst Center
      cisco.dnac.user_role_workflow_manager:
        <<: *dnac_login
        state: merged
        config: "{{roles_users_details}}"
      register: role_user_output
    - name: Print the roles and users creation output
      debug:
        msg: "{{role_user_output}}"
    - name: Roles and Users playbook end time
      set_fact:
        long_op_end: "{{ now() }}"
    - name: Print Roles and Users playbook execution time
      debug:
        msg: "Roles and Users playbook run time: {{ long_op_start }}, end: {{ long_op_end }}"
  post_tasks:
    - name: run command module to find python version
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local