---
#Select Catalyst Cennter version, this one overwrite the default version from host file
catalyst_center_version: 2.3.7.6
catalyst_center_task_timeout: 1200
catalyst_center_task_poll_interval: 60

# Network Settings an IP Pools design.
device_configs_backup_details:
  - management_ip_address: 204.1.2.1
    #hostname: NY-BN-9500.cisco.local
    #serial_number: F2AKI0082J
    #family: Switches and Hubs
    #type: Cisco Catalyst 9300 Switch
    #series: Cisco Catalyst 9300 Series Switches
    collection_status: Managed
    file_path: "./"
  - management_ip_address: 204.1.2.2
    file_path: "./"

