---
- import_playbook: ../../sda_device_removal_and_unprovision/playbook/sda_device_removal_and_unprovision_playbook.yml
  vars:
    VARS_FILE_PATH: "{{ lookup('env', 'PWD') }}/workflows/switch_refresh_regression/vars/cleanup_lan_automation_enl1.yml"
