---
# Playbook for LAN Automation on Cisco Catalyst Center
- name: Cisco Catalyst Center LAN Automation
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILE_PATH }}"

  vars:
    state: merged
    catalyst_center_login: &catalyst_center_login
      dnac_host: "{{ catalyst_center_host | default(dnac_host) }}"
      dnac_username: "{{ catalyst_center_username | default(dnac_username) }}"
      dnac_password: "{{ catalyst_center_password | default(dnac_password) }}"
      dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
      dnac_port: "{{ catalyst_center_port | default(443) }}"
      dnac_verify: "{{ catalyst_center_verify | default(dnac_verify) }}"
      config_verify: "{{ catalyst_center_config_verify | default(False) }}"
      dnac_debug: "{{ catalyst_center_debug | default(False) }}"
      dnac_log: "{{ catalyst_center_log | default(False) }}"
      dnac_log_level: "{{ catalyst_center_log_level | default('INFO') }}"
      dnac_log_file_path: "{{ catalyst_center_log_file_path |  default(omit) }}"
      dnac_log_append: "{{ catalyst_center_log_append |  default(False) }}"
  tasks:
    - name: Include LAN Automation Variables
      include_vars:
        file: "{{ VARS_FILE_PATH }}"
      when: VARS_FILE_PATH is defined

    - name: Set LAN Automation Start Time
      set_fact:
        long_op_start: "{{ now() }}"

    - name: Run LAN Automation Workflows
      cisco.dnac.lan_automation_workflow_manager:
        <<: *catalyst_center_login
        config: 
          - "{{ item }}"
      loop: "{{ lan_automation_details.lan_automation_session }}"
      when: lan_automation_details.lan_automation_session is defined
      register: lan_automation_output

    - name: Print LAN Automation Output
      debug:
        msg: "{{ lan_automation_output }}"
      when: lan_automation_output is defined

    - name: Update LAN Automated devices
      cisco.dnac.lan_automation_workflow_manager:
        <<: *catalyst_center_login
        config: 
          - "{{ item }}"
      register: loopback_update_output
      loop: "{{ lan_automation_details.device_update }}"
      when: lan_automation_details.device_update is defined

    - name: Print Loopback Update Output
      debug:
        msg: "{{ loopback_update_output }}"
      when: loopback_update_output is defined

    - name: Set LAN Automation End Time
      set_fact:
        long_op_end: "{{ now() }}"

    - name: Print LAN Automation Execution Time
      debug:
        msg: "LAN Automation runtime: Start {{ long_op_start }}, End {{ long_op_end }}"

    - name: Check Python Version on Catalyst Center Host
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local
