---
- name: Stop LAN Automation on Cisco Catalyst Center
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILE_PATH }}"
  
  vars:
    state: deleted
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ catalyst_center_version | default(dnac_version) }}"
      dnac_debug: "{{ dnac_debug }}"
      dnac_log: "{{ dnac_log }}"
      dnac_log_level: "{{ dnac_log_level }}"

  tasks:
    - name: Print VARS_FILE_PATH
      debug:
        msg: "Input file selected: {{ VARS_FILE_PATH }}"

    - name: Set Start Time for Stopping LAN Automation
      set_fact:
        long_op_start: "{{ now() }}"

    - name: Stop LAN Automation Session in file "{{ VARS_FILE_PATH }}" and state "{{ state }}"
      cisco.dnac.lan_automation_workflow_manager:
        <<: *dnac_login
        state: "{{ state }}"
        config: 
          - "{{ item }}"
      loop: "{{ lan_automation_details.lan_automation_session }}"
      when: lan_automation_details.lan_automation_session is defined

    - name: Set End Time for Stopping LAN Automation
      set_fact:
        long_op_end: "{{ now() }}"

    - name: Print LAN Automation Stop Execution Time
      debug:
        msg: "LAN Automation stop runtime: Start {{ long_op_start }}, End {{ long_op_end }}"

  post_tasks:
    - name: Run Command to Find Python Version
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local

