---
cli:
  - global_credential_details:
      cli_credential:
        - description: cli
          username: cisco
          password: Public#123
          enable_password: Public#123

snmpv2c_read:
  - global_credential_details:
      snmp_v2c_read:
        - description: snmpRead
          read_community: Public#123

snmpv2c_write:
  - global_credential_details:
      snmp_v2c_write:
        - description: snmpWrite
          write_community: Public#123

snmpv3:
  - global_credential_details:
      snmp_v3:
        - description: SNMPv3-credentials
          username: cisco
          auth_password: Public#123456789
          auth_type: SHA
          snmp_mode: AUTHPRIV
          privacy_type: AES128
          privacy_password: Public#1234567890

https_read:
  - global_credential_details:
      https_read:
        - description: http_read
          username: cisco
          password: Public#123
          port: 443

https_write:
  - global_credential_details:
      https_write:
        - description: http_write
          username: cisco
          password: Public#123
          port: 443

all_creds:
  - global_credential_details:
      cli_credential:
        - description: cli
          username: cisco
          password: Public#123
          enable_password: Public#123
      snmp_v2c_read:
        - description: snmpRead
          read_community: Public#123
      snmp_v2c_write:
        - description: snmpWrite
          write_community: Public#123
      snmp_v3:
        - description: SNMPv3-credentials
          username: cisco
          auth_password: Public#123456789
          auth_type: SHA
          snmp_mode: AUTHPRIV
          privacy_type: AES128
          privacy_password: Public#1234567890
      https_read:
        - description: http_read
          username: cisco
          password: Public#123
          port: 443
      https_write:
        - description: http_write
          username: cisco
          password: Public#123
          port: 443

all_cli:
  - global_credential_details:
      cli_credential:
        - description: Cisco
          username: cisco
          password: Public#123
          enable_password: Public#123

all_snmp:
  - global_credential_details:
      snmp_v2c_read:
        - description: snmpRead
          read_community: Public#123
      snmp_v2c_write:
        - description: snmpWrite
          write_community: Public#123
  - global_credential_details:
      snmp_v3:
        - description: SNMPv3-credentials
          username: cisco
          auth_password: Public#123456789
          auth_type: SHA
          snmp_mode: AUTHPRIV
          privacy_type: AES128
          privacy_password: Public#1234567890

all_https:
  - global_credential_details:
    https_read:
      - description: http_read
        username: cisco
        password: Public#123
        port: 443
    https_write:
      - description: http_write
        username: cisco
        password: Public#123
        port: 443

assign:
  - assign_credentials_to_site: # Assign device credentials to sites
      cli_credential:
        description: cli
        username: cisco
      snmp_v3:
        description: SNMPv3-credentials
      https_read:
        username: cisco
        description: http_read
      https_write:
        username: cisco
        description: http_write
      site_name:
        - Global
