---
# This file contains the variables for the inventory workflow
inventory_details:
  network_devices:
    - ip_address:
      - 204.101.16.1
      provision_wired_device:
        site_name: Global/USA/SAN JOSE/BLD23
      device_resync: true
      force_sync: true
    - ip_address:
      - 204.101.16.4
      provision_wired_device:
        site_name: Global/USA/SAN JOSE/BLD23
      device_resync: true
      force_sync: true
    - ip_address:
      - 204.101.48.2
      provision_wired_device:
        site_name: Global/USA/SAN JOSE/BLD23/FLOOR1_LEVEL1
      cli_transport: SSH
      compute_device: false
      enable_password: Lablab#123
      http_password: Lablab#123
      http_secure: true
      http_username: wlcaccess
      netconf_port: 430
      password: Lablab#123
      snmp_auth_passphrase: "hp!x6px&#@2xi5"
      snmp_auth_protocol: SHA
      snmp_mode: AUTHPRIV
      snmp_priv_passphrase: "ai7tpci3j@*j5g"
      snmp_priv_protocol: AES128
      snmp_retry: 3
      snmp_timeout: 5
      snmp_username: wlcaccess
      snmp_version: 3
      device_added: true
      username: wlcaccess
      force_sync: true
      device_resync: true
    - ip_address:
      - 204.101.16.3
      provision_wired_device:
        site_name: Global/USA/SAN JOSE/BLD23/FLOOR1_LEVEL1
      cli_transport: SSH
      compute_device: false
      enable_password: Lablab#123
      http_password: Lablab#123
      http_secure: true
      http_username: wlcaccess
      netconf_port: 430
      password: Lablab#123
      snmp_auth_passphrase: "hp!x6px&#@2xi5"
      snmp_auth_protocol: SHA
      snmp_mode: AUTHPRIV
      snmp_priv_passphrase: "ai7tpci3j@*j5g"
      snmp_priv_protocol: AES128
      snmp_retry: 3
      snmp_timeout: 5
      snmp_username: wlcaccess
      snmp_version: 3
      device_added: true
      username: wlcaccess
      force_sync: true
      device_resync: true