---
#Select Catalyst Cennter version, this one overwrite the default version from host file
catalyst_center_version: 2.3.7.6
# This file contains the variables for the inventory workflow
inventory_details:
  network_devices:
  - ip_address_list: ["204.101.16.1","204.101.16.2"]
    device_resync: True
    # Make this True if you want to force resync the device
    force_sync: False
    resync_retry_count: 200
    resync_interval: 2
    # Make this True if you want to reboot the device
    reboot_device: True