---
# tasks file for credentials

- name: Includes Credentials info
  include_vars:
    file: "{{ credentials_input_file }}"
    name: vars_map
  tags: always

- name: Create All Credentials at once
  cisco.dnac.device_credential_workflow_manager:
    dnac_host: "{{ dnac_host }}"
    dnac_username: "{{ dnac_username }}"
    dnac_password: "{{ dnac_password }}"
    dnac_verify: "{{ dnac_verify }}"
    dnac_port: "{{ dnac_port }}"
    dnac_version: "{{ dnac_version }}"
    dnac_debug: "{{ dnac_debug }}"
    dnac_log_level: "{{ dnac_log_level }}"
    config_verify: True
    state: merged
    config:
      - "{{ item }}"
  loop: "{{ vars_map.all_creds }}"
  tags: create_creds

- name: Delete All Credentials at once
  cisco.dnac.device_credential_workflow_manager:
    dnac_host: "{{ dnac_host }}"
    dnac_username: "{{ dnac_username }}"
    dnac_password: "{{ dnac_password }}"
    dnac_verify: "{{ dnac_verify }}"
    dnac_port: "{{ dnac_port }}"
    dnac_version: "{{ dnac_version }}"
    dnac_debug: "{{ dnac_debug }}"
    dnac_log_level: "{{ dnac_log_level }}"
    config_verify: True
    state: deleted
    config:
      - "{{ item }}"
  with_list: "{{ vars_map.all_creds }}"
  tags: delete_creds

- name: Assign Credentials to sites
  cisco.dnac.device_credential_workflow_manager:
    dnac_host: "{{ dnac_host }}"
    dnac_username: "{{ dnac_username }}"
    dnac_password: "{{ dnac_password }}"
    dnac_verify: "{{ dnac_verify }}"
    dnac_port: "{{ dnac_port }}"
    dnac_version: "{{ dnac_version }}"
    dnac_debug: "{{ dnac_debug }}"
    dnac_log_level: "{{ dnac_log_level }}"
    config_verify: True
    state: merged
    config:
      - "{{ item }}"
  with_list: "{{ vars_map.assign }}"
  tags: assign_creds
