---
- name: Playbook to manage Cisco Catalyst Center Device Discovery
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILE_PATH }}"
  vars:
    state: merged
    catalyst_center_login: &catalyst_center_login
      dnac_host: "{{ catalyst_center_host | default(dnac_host) }}"
      dnac_username: "{{ catalyst_center_username | default(dnac_username) }}"
      dnac_password: "{{ catalyst_center_password | default(dnac_password) }}"
      dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
      dnac_port: "{{ catalyst_center_port | default(443) }}"
      dnac_verify: "{{ catalyst_center_verify | default(dnac_verify) }}"
      config_verify: "{{ catalyst_center_config_verify | default(False) }}"
      dnac_debug: "{{ catalyst_center_debug | default(False) }}"
      dnac_log: "{{ catalyst_center_log | default(False) }}"
      dnac_log_level: "{{ catalyst_center_log_level | default('INFO') }}"
      dnac_log_file_path: "{{ catalyst_center_log_file_path |  default(omit) }}"
      dnac_log_append: "{{ catalyst_center_log_append |  default(False) }}"
      dnac_api_task_timeout: "{{ catalyst_center_api_task_timeout |  default(1200) }}"

  tasks:
    - name: print VARS_FILE_PATH
      debug:
        msg: "Input file selected {{ VARS_FILE_PATH }}"
    - name: Playbook start time for the discoveries
      set_fact:
        long_op_start: "{{ now() }}"
    - name: Discover a singe device IP Address for a list of discoveries from "{{ VARS_FILE_PATH }}"
      cisco.dnac.discovery_workflow_manager:
        <<: *catalyst_center_login
        state: "{{ state }}"
        config:
        - "{{ item }}"
      loop: "{{ discovery_details.single }}"
      when: discovery_details.single is defined

    - name: Discover devices for an IP Address Range if defined in file "{{ VARS_FILE_PATH }}"
      cisco.dnac.discovery_workflow_manager:
        <<: *catalyst_center_login
        state: "{{ state }}"
        config:
        - "{{ item }}"
      loop: "{{ discovery_details.range }}"
      when: discovery_details.range is defined

    - name: Discover Multi IP Address Ranges if defined in the file "{{ VARS_FILE_PATH }}"
      cisco.dnac.discovery_workflow_manager:
        <<: *catalyst_center_login
        state: "{{ state }}"
        config:
        - "{{ item }}"
      loop: "{{ discovery_details.multi_range }}"
      when: discovery_details.multi_range is defined

    - name: Discover devices from a CDP seed if defined in the file "{{ VARS_FILE_PATH }}"
      cisco.dnac.discovery_workflow_manager:
        <<: *catalyst_center_login
        state: "{{ state }}"
        config:
        - "{{ item }}"
      loop: "{{ discovery_details.cdp }}"
      when: discovery_details.cdp is defined

    - name: Discover devices from an LLDP seed if defined in the file "{{ VARS_FILE_PATH }}"
      cisco.dnac.discovery_workflow_manager:
        <<: *catalyst_center_login
        state: "{{ state }}"
        config:
        - "{{ item }}"
      loop: "{{ discovery_details.lldp }}"
      when: discovery_details.lldp is defined

    - name: Configure and run an CIDR Discovery if defined in the file "{{ VARS_FILE_PATH }}"
      cisco.dnac.discovery_workflow_manager:
        <<: *catalyst_center_login
        state: "{{ state }}"
        config:
        - "{{ item }}"
      loop: "{{ discovery_details.cidr }}"
      when: discovery_details.cidr is defined
    - name: Discovery playbook end time
      set_fact:
        long_op_end: "{{ now() }}"
    - name: Print Discovery playbook execution time
      debug:
        msg: "Discovery playbook run time: {{ long_op_start }}, end: {{ long_op_end }}"
  post_tasks:
    - name: run command module to find python version
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local