---
- name: Configure Sites on Cisco DNA Center which includes Areas, Buildings, and Floors
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILE_PATH }}"

  vars:
    state: deleted
    catalyst_center_login: &catalyst_center_login
      dnac_host: "{{ catalyst_center_host | default(dnac_host) }}"
      dnac_username: "{{ catalyst_center_username | default(dnac_username) }}"
      dnac_password: "{{ catalyst_center_password | default(dnac_password) }}"
      dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
      dnac_port: "{{ catalyst_center_port | default(443) }}"
      dnac_verify: "{{ catalyst_center_verify | default(dnac_verify) }}"
      config_verify: "{{ catalyst_center_config_verify | default(False) }}"
      dnac_debug: "{{ catalyst_center_debug | default(False) }}"
      dnac_log: "{{ catalyst_center_log | default(False) }}"
      dnac_log_level: "{{ catalyst_center_log_level | default('INFO') }}"
      dnac_log_file_path: "{{ catalyst_center_log_file_path |  default(omit) }}"
      dnac_log_append: "{{ catalyst_center_log_append |  default(False) }}"
  tasks:
    - name: Site Playbook start time
      set_fact:
        long_op_start: "{{ now() }}"
    - set_fact:
        dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
    - set_fact:
        config_verify: "{{ catalyst_center_config_verify | default(False) }}"
        
    - name: Delete sites from design_sites config
      cisco.dnac.site_workflow_manager:
        <<: *catalyst_center_login
        state: "{{state}}"
        config: "{{design_sites}}"
    - name: Sites delete playbook end time
      set_fact:
        long_op_end: "{{ now() }}"

    - name: Print sites execution time
      debug:
        msg: "Sites playbook run time: {{ long_op_start }}, end: {{ long_op_end }}"

  post_tasks:
    - name: run command module to find python version
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local
