---
- name: Configure Sites on Cisco DNA Center which includes Areas, Buildings, and Floors
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILES_PATH }}"

  vars:
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"

  tasks:
    - name: Create sites from design_sites config
      cisco.dnac.site_intent:
        <<: *dnac_login
        state: merged
        config:
          - "{{ item }}"
      loop: "{{ design_sites }}"
