---
- name: Configure Sites on Cisco Catalyst Center which includes Areas, Buildings, and Floors
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no
  vars_files:
    - "{{ VARS_FILE_PATH }}"

  vars:
    state: merged
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"

  tasks:
    - name: Create sites from design_sites config
      cisco.dnac.site_workflow_manager:
        <<: *dnac_login
        state: "{{state}}"
        config: "{{design_sites}}"
      #loop: "{{ design_sites }}"
