---
- name:  Delete assignment of the wireless SSIDs, Enterprise SSIDs, and Guest SSIDs on Cisco Catalyst Center to the wireless NW profiles for sites
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no
  vars_files:
    - "{{ VARS_FILE_PATH }}"
  vars:
    state: deleted
    catalyst_center_login: &catalyst_center_login
      dnac_host: "{{ catalyst_center_host | default(dnac_host) }}"
      dnac_username: "{{ catalyst_center_username | default(dnac_username) }}"
      dnac_password: "{{ catalyst_center_password | default(dnac_password) }}"
      dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
      dnac_port: "{{ catalyst_center_port | default(443) }}"
      dnac_verify: "{{ catalyst_center_verify | default(dnac_verify) }}"
      config_verify: "{{ catalyst_center_config_verify | default(False) }}"
      dnac_debug: "{{ catalyst_center_debug | default(False) }}"
      dnac_log: "{{ catalyst_center_log | default(False) }}"
      dnac_log_level: "{{ catalyst_center_log_level | default('INFO') }}"
      dnac_log_file_path: "{{ catalyst_center_log_file_path |  default(omit) }}"
      dnac_log_append: "{{ catalyst_center_log_append |  default(False) }}"
  tasks:
    # Include the variables file {{ VARS_FILE_PATH }} for the playbook
    - name: Include the variables file {{ VARS_FILE_PATH }} for the playbook
      include_vars:
        file: "{{ VARS_FILE_PATH }}"
    # set the password file path
    - name: set the password file path
      set_fact:
        passwords_file: "{{ passwords_file  | default('../../../ansible_vault_encrypted_inputs/mypasswordfile.yaml') }}"
      when: jinjatemplate is defined and jinjatemplate is true 
    # load password file
    - name: load password file
      include_vars:
        file: "{{ passwords_file }}"
      when: jinjatemplate is defined and jinjatemplate is true and passwords_file is defined
    # Create inputs from the Jinja Template
    - name: Create inputs from the Jinja Template
      template: 
        src: "{{ jinjatemplate_file }}"
        dest: ../tmp/template_generated_file.yaml
      when:  jinjatemplate is defined and jinjatemplate is true and jinjatemplate_file is defined

    # Include the variables file {{ VARS_FILE_PATH }} for the playbook
    - name: Include the variables file {{ VARS_FILE_PATH }} for the playbook
      include_vars:
        file: ../tmp/template_generated_file.yaml
      when: jinjatemplate is defined
    # Include the variables file {{ VARS_FILE_PATH }} for the playbook
    - name: Include the variables file {{ VARS_FILE_PATH }} for the playbook
      include_vars:
        file: "{{ VARS_FILE_PATH }}"
      when: jinjatemplate is not defined or jinjatemplate is false
    - name: Start time for the playbook
      set_fact:
        long_op_start: "{{ now() }}"
    - name: Create the Wireless SSID, Interfaces, Custom RF Profiles, etc.
      cisco.dnac.network_profile_wireless_workflow_manager:
        <<: *catalyst_center_login
        state: "{{ state }}"
        config: "{{wireless_nw_profiles_details}}"
      register: wireless_nw_profiles_output
    - name: Print the output of the Wireless SSID, Interfaces, Custom RF Profiles, etc.
      debug:
        msg: "{{wireless_nw_profiles_output}}"
    - name: End time for the playbook
      set_fact:
        long_op_end: "{{ now() }}"
    - name: Wireless SSID, Interfaces, Custom RF Profiles, etc. playbook run time
      debug:
        msg: "Playbook run time is run time: {{ long_op_start }}, end: {{ long_op_end }}"
      when: long_op_start is defined and long_op_end is defined
    - name: Remove the template generated file
      file:
        path: ../tmp/template_generated_file.yaml
        state: absent
      when: jinjatemplate is defined and jinjatemplate is true and jinjatemplate_file is defined
      # End of playbook