# The following playbook is use to re-provision devices on Cisco Catalyst Center
# The playbook is executed with the following command
# ansible-playbook -i inventory/hosts.yml reprovision_workflow_playbook.yml --extra-vars "VARS_FILES_PATH=../vars/reprovision_workflow_inputs.yml"
- name: Re_Provision devices Cisco Catalyst Center
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILE_PATH }}"

  vars:
    state: merged
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_port: "{{ dnac_port }}"
      dnac_verify: "{{ dnac_verify }}"
      config_verify: "{{ catalyst_center_config_verify | default(False) }}"
      dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
      dnac_debug: "{{ catalyst_center_debug | default(dnac_debug) }}"
      dnac_log: "{{ catalyst_center_log | default(dnac_log) }}"
      dnac_log_level: "{{ catalyst_center_log_level | default(dnac_log_level) }}"
      dnac_log_file_path: "{{ catalyst_center_log_file_path | default(dnac_log_file_path) }}"
      dnac_log_append: "{{ catalyst_center_log_append | default(dnac_log_append) }}"

  tasks:
    - name: Re-Provision devices on Cisco Catalyst Center
      set_fact:
        long_op_start: "{{ now() }}"
    - name: Re-Provision devices on Cisco Catalyst Center
      cisco.dnac.provision_workflow_manager:
        <<: *dnac_login
        state: merged
        config: "{{reprovision_details}}"
      register: reprovision_output
      when: reprovision_details is defined
    - name: Print the ReProvision devices output
      debug:
        msg: "{{reprovision_output}}"
    - name: ReProvision devices playbook end time
      set_fact:
        long_op_end: "{{ now() }}"
    - name: Print ReProvision devices playbook execution time
      debug:
        msg: "ReProvision devices playbook run time: {{ long_op_start }}, end: {{ long_op_end }}"
  post_tasks:
    - name: run command module to find python version
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local
