
---
- name: Configure global credentials on Cisco DNA Center
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars:
    wireless_sensors: []
    unified_aps: []
    network_devices: []
    dnac_login: &dnac_login
                
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
      dnac_log: "{{ dnac_log | }}"
      dnac_log_level: "{{ dnac_log_level | default('INFO') }}"

  tasks:
    - name: Combine all inventory to have a full inventory.
      set_fact:
        dnac_inv:  "{{ {'catalyst_center_hosts':{ 'hosts': {inventory_hostname: {'dnac_host': dnac_host, 'dnac_username': dnac_username,\
                   'dnac_password': dnac_password, 'dnac_verify': dnac_verify, 'dnac_port': dnac_port,\
                   'dnac_version':dnac_version, 'dnac_debug':dnac_debug }}}} }} "
    - name: Create Hosts list.
      set_fact:
        dnac_hosts:  "{{ {'catalyst_center_hosts':{ 'hosts': 'dnaccluster1' }} }} "
    - name: Creates directory
      file:
        path: "../../../host_inventory_{{inventory_hostname}}_{{dnac_host}}"
        state: directory
    - name: Creates directory
      file:
        path: "../../../host_inventory_{{inventory_hostname}}_{{dnac_host}}/group_vars"
        state: directory
    - name: Yaml dump hosts data to yaml file hosts.yaml
      copy:
        content: "{{ dnac_inv | to_nice_yaml }}"
        dest: "../../../host_inventory_{{inventory_hostname}}_{{dnac_host}}/hosts.yml"
        force: yes
    - name: set fact to set group vars
      set_fact:
        group_vars:  "{{ { } }} "
    - name: Yaml dump network device data with formatted output to file  inv_network_devices.yml
      copy:
        content: "{{ group_vars | to_nice_yaml }}"
        dest: "../../../host_inventory_{{inventory_hostname}}_{{dnac_host}}/group_vars/all.yml"
        force: yes
...
