ise_hostname: ise.example.com
ise_username: admin
ise_password: your_ise_password

security_groups:
  - name: Employees
    description: Group for employees
  - name: Guests
    description: Group for guests
  - name: Servers
    description: Group for servers

access_contracts:
  - name: Employee_to_Server
    description: Allow employees to access servers
    source_group: Employees
    destination_group: Servers
  - name: Guest_to_Internet
    description: Allow guests to access the internet
    source_group: Guests
    destination_group: Any

access_policies:
  - name: Policy1
    description: Apply Employee_to_Server contract
    contract: Employee_to_Server
  - name: Policy2
    description: Apply Guest_to_Internet contract
    contract: Guest_to_Internet