---
#the following playbook is used to delete Authentication and Policy Servers  on Cisco Catalyst Center
# The playbook is executed with the following command
# Manage operations on Authentication and Policy Servers.
# API to delete Authentication and Policy Server Access Configuration.
# ansible-playbook -i inventory/hosts.yml workflows/ise_radius_integration/playbook/delete_ise_radius_integration_workflow_playbook.yml --extra-vars "VARS_FILES_PATH=../vars/ise_radius_integration_workflow_input.yml"
- name: Network Compliance on  Cisco Catalyst Center
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILE_PATH }}"

  vars:
    state: deleted
    dnac_login: &dnac_login
      dnac_host: "{{ catalyst_center_host | default(dnac_host) }}"
      dnac_username: "{{ catalyst_center_username | default(dnac_username) }}"
      dnac_password: "{{ catalyst_center_password | default(dnac_password) }}"
      dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
      dnac_port: "{{ catalyst_center_port | default(443) }}"
      dnac_verify: "{{ catalyst_center_verify | default(dnac_verify) }}"
      config_verify: "{{ catalyst_center_config_verify | default(False) }}"
      dnac_debug: "{{ catalyst_center_debug | default(False) }}"
      dnac_log: "{{ catalyst_center_log | default(False) }}"
      dnac_log_level: "{{ catalyst_center_log_level | default('INFO') }}"
      dnac_log_file_path: "{{ catalyst_center_log_file_path |  default(omit) }}"
      dnac_log_append: "{{ catalyst_center_log_append |  default(False) }}"
  tasks:
    - name: Playbook start time for Authentication and Policy Servers deletion on Cisco Catalyst Center
      set_fact:
        long_op_start: "{{ now() }}"
    - name: Authentication and Policy Servers deletion on Cisco Catalyst Center
      cisco.dnac.ise_radius_integration_workflow_manager:
        <<: *dnac_login
        state: deleted
        config: "{{ise_radius_integration_details}}"
      register: ise_radius_integration_output
      #when: ise_radius_integration_details is defined
    - name: Print the Authentication and Policy Servers deletion output
      debug:
        msg: "{{ise_radius_integration_output}}"
    - name: Authentication and Policy Servers deletion playbook end time
      set_fact:
        long_op_end: "{{ now() }}"
    - name: Print Authentication and Policy Servers deletion playbook execution time
      debug:
        msg: "Authentication and Policy Servers deletion playbook run time: {{ long_op_start }}, end: {{ long_op_end }}"
  post_tasks:
    - name: run command module to find python version
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local
