---
#the following playbook is used to configure Authentication and Policy Servers  on Cisco Catalyst Center
# The playbook is executed with the following command
# Manage operations on Authentication and Policy Servers.
# API to create Authentication and Policy Server Access Configuration.
# API to update Authentication and Policy Server Access Configuration.
# ansible-playbook -i inventory/hosts.yml workflows/ise_radius_integration/playbook/ise_radius_integration_workflow_playbook.yml --extra-vars "VARS_FILES_PATH=../vars/ise_radius_integration_workflow_input.yml"
- name: ISE Integration on  Cisco Catalyst Center
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILE_PATH }}"

  vars:
    state: merged
    catalyst_center_login: &catalyst_center_login
      dnac_host: "{{ catalyst_center_host | default(dnac_host) }}"
      dnac_username: "{{ catalyst_center_username | default(dnac_username) }}"
      dnac_password: "{{ catalyst_center_password | default(dnac_password) }}"
      dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
      dnac_port: "{{ catalyst_center_port | default(443) }}"
      dnac_verify: "{{ catalyst_center_verify | default(dnac_verify) }}"
      config_verify: "{{ catalyst_center_config_verify | default(False) }}"
      dnac_debug: "{{ catalyst_center_debug | default(False) }}"
      dnac_log: "{{ catalyst_center_log | default(False) }}"
      dnac_log_level: "{{ catalyst_center_log_level | default('INFO') }}"
      dnac_log_file_path: "{{ catalyst_center_log_file_path |  default(omit) }}"
      dnac_log_append: "{{ catalyst_center_log_append |  default(False) }}"
      dnac_api_task_timeout: "{{ catalyst_center_api_task_timeout |  default(1200) }}"
      
  # Tasks including jinja templates to create the ise_radius_integration_details
  tasks:
    - name: Playbook start time for Authentication and Policy Servers configuration on Cisco Catalyst Center
      set_fact:
        long_op_start: "{{ now() }}"

    - name: set the password file path
      set_fact:
        passwords_file: "{{ passwords_file  | default('../../../ansible_vault_encrypted_inputs/mypasswordfile.yaml') }}"
      when: jinjatemplate is defined and jinjatemplate is true 

    - name: load password file
      include_vars:
        file: "{{ passwords_file }}"
      when: jinjatemplate is defined and jinjatemplate is true and passwords_file is defined

    # load ise_radius_integration_details template jinja file
    - name: Load template file to create Authentication and Policy Servers
      template: 
        src: "{{ jinjatemplate_file }}"
        dest: ../tmp/template_generated_file.yaml
      when:  jinjatemplate is defined and jinjatemplate is true and jinjatemplate_file is defined
    # Include the variables file ../tmp/template_generated_file.yaml for the playbook
    - name: Include the variables file ../tmp/template_generated_file.yaml for the playbook
      include_vars:
        file: ../tmp/template_generated_file.yaml
      when: jinjatemplate is defined and jinjatemplate is true and jinjatemplate_file is defined
    - name: Authentication and Policy Servers configurations on Cisco Catalyst Center
      cisco.dnac.ise_radius_integration_workflow_manager:
        <<: *catalyst_center_login
        state: merged
        config: "{{ise_radius_integration_details}}"
      register: ise_radius_integration_output
      when: ise_radius_integration_details is defined and ise_radius_integration_details | length > 0
    - name: Print the Authentication and Policy Servers configuration output
      debug:
        msg: "{{ise_radius_integration_output}}"
      when: ise_radius_integration_output is defined
    # delete the template file
    - name: Delete the template file
      ansible.builtin.command: rm ../tmp/template_generated_file.yaml
      when:  jinjatemplate is defined and jinjatemplate is true and jinjatemplate_file is defined
    - name: Authentication and Policy Servers configuration playbook end time
      set_fact:
        long_op_end: "{{ now() }}"
    - name: Print Authentication and Policy Servers configuration playbook execution time
      debug:
        msg: "Authentication and Policy Servers configuration playbook run time: {{ long_op_start }}, end: {{ long_op_end }}"
  post_tasks:
    - name: run command module to find python version
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local

