---
# tasks file for swim
- name: Includes SWIM info
  include_vars:
    file: "{{ swim_input_file }}"
    name: vars_map
  tags: always

- name: SWIM a device end-to-end
  cisco.dnac.swim_workflow_manager:
    dnac_host: "{{ dnac_host }}"
    dnac_username: "{{ dnac_username }}"
    dnac_password: "{{ dnac_password }}"
    dnac_verify: "{{ dnac_verify }}"
    dnac_port: "{{ dnac_port }}"
    dnac_version: "{{ dnac_version }}"
    dnac_debug: "{{ dnac_debug }}"
    dnac_log: "{{ dnac_log }}"
    dnac_log_level: "{{ dnac_log_level }}"
    config_verify: True
    config:
      - "{{ item }}"
  loop: "{{ vars_map.device_e2e }}"
  tags: swim_single_device

- name: SWIM a filtered devices list end-to-end
  cisco.dnac.swim_workflow_manager:
    dnac_host: "{{ dnac_host }}"
    dnac_username: "{{ dnac_username }}"
    dnac_password: "{{ dnac_password }}"
    dnac_verify: "{{ dnac_verify }}"
    dnac_port: "{{ dnac_port }}"
    dnac_version: "{{ dnac_version }}"
    dnac_debug: "{{ dnac_debug }}"
    dnac_log: "{{ dnac_log }}"
    dnac_log_level: "{{ dnac_log_level }}"
    config_verify: True
    config:
      - "{{ item }}"
  loop: "{{ vars_map.filter_e2e }}"
  tags: swim_with_filter
