---
- name: Configure device credentials on Cisco Catalyst Center Center
  hosts: dnachosts
  connection: local
  gather_facts: no
  no_log: false
  
  vars_files:
    - "{{ VARS_FILES_PATH }}"

  vars:
    STATE: "present"
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"

  tasks:
    - name: print global_ippools
      debug:
        msg: "{{ global_ippools }}"

    - name: Create Global IP Pools
      cisco.dnac.global_pool:
        <<: *dnac_login
        state: "{{ STATE }}"
        settings:
          ippool: "{{ [item]}}"
      register: global_ippools_result
      loop: "{{ global_ippools.ippool }}"

    - name: Print Global IP Pools Result
      debug:
        msg: "{{ global_ippools_result }}"
    #count the success result and the failure device_details.results | selectattr('success', 'equalto', True) | list | count
    - name: Print Global IP Pools Success Count
      debug:
        msg: "{{ global_ippools_result.results | selectattr('failed', 'equalto', False) | list | count }}"
    - name: Print Global IP Pools Failure Count
      debug:
        msg: "{{ global_ippools_result.results | selectattr('failed', 'equalto', True) | list | count }}"

  