---
#the following playbook is used to Delete roles with specific permissions and users with the specific roles on Cisco Catalyst Center
# The user need to be having super-admin access to run this playbook to create or update roles or users.
# The roles should be created before creating the users to assign the roles to the users.
# The playbook is executed with the following command
# ansible-playbook -i inventory/hosts users_and_roles_playbook.yml --extra-vars "VARS_FILES_PATH=../vars/users_and_roles_inputs.yml"
- name: Delete Roles and Users with given roles on Cisco Catalyst Center
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILE_PATH }}"

  vars:
    state: deleted
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
      dnac_debug: "{{ dnac_debug }}"
      dnac_log: "{{ dnac_log }}"
      dnac_log_level: "{{ dnac_log_level }}"
      dnac_log_file_path: "{{ catalyst_center_log_file_path | default(dnac_log_file_path) }}"
      dnac_log_append: "{{ catalyst_center_log_append | default(dnac_log_append) }}"
  tasks:
    - name: Delete the roles and users on Cisco Catalyst Center
      set_fact:
        long_op_start: "{{ now() }}"
    - name: Delete the given roles and users on Cisco Catalyst Center
      cisco.dnac.user_role_workflow_manager:
        <<: *dnac_login
        state: deleted
        config: "{{roles_users_details}}"
      register: role_user_output
    - name: Print the roles and users Delete output
      debug:
        msg: "{{role_user_output}}"
    - name: Delete Roles and Users playbook end time
      set_fact:
        long_op_end: "{{ now() }}"
    - name: Print Delete Roles and Users playbook execution time
      debug:
        msg: "Delete Roles and Users playbook run time: {{ long_op_start }}, end: {{ long_op_end }}"
  post_tasks:
    - name: run command module to find python version
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local
