---
- name: Playbook for ISE and AAA integration module (for set up)
  hosts: dnac
  connection: local
  gather_facts: no

  vars_files:
    - cc_config.yml
    - "{{ config_ise_aaa }}"

  vars:
    common_config: &common_config
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
      dnac_log: "{{ dnac_log }}"
      dnac_log_level: "{{ dnac_log_level }}"
      config_verify: True

  tasks:
    - name: Includes ISE_AAA info
      include_vars:
        file: "{{ input_file }}"
        name: vars_map
      tags: always

    - name: Add ISE and AAA server
      cisco.dnac.ise_radius_integration_workflow_manager:
        <<: *common_config
        state: merged
        config:
            - authentication_policy_server:
              - server_type: AAA
                server_ip_address: 204.192.1.249
                shared_secret: xxxx
                protocol: RADIUS_TACACS
            - authentication_policy_server:
              - server_type: AAA
                server_ip_address: 204.192.1.252
                shared_secret: xxxx
                protocol: RADIUS_TACACS
            - authentication_policy_server:
              - server_type: ISE
                server_ip_address: 172.23.241.229
                shared_secret: xxxx
                protocol: RADIUS_TACACS
                encryption_scheme: KEYWRAP
                encryption_key: xxxx
                message_authenticator_code_key: xxxx
                authentication_port: 1812
                accounting_port: 1813
                retries: 3
                timeout: 4
                role: primary
                use_dnac_cert_for_pxgrid: False
                pxgrid_enabled: True
                cisco_ise_dtos:
                  - user_name: xxxx
                    password: xxxx
                    fqdn: IAC2-ISE-VM-1.cisco.local
                    ip_address: 172.23.241.229
                    description: Cisco ISE
                trusted_server: True
      tags: ise_aaa_intg
