---
#the following playbook is used to run compliance, fix config compliance, on Cisco Catalyst Center
# The playbook is executed with the following command
# ansible-playbook -i inventory/hosts.yml network_compliance_playbook.yml --extra-vars "VARS_FILES_PATH=../vars/network_compliance_inputs.yml"
- name: Network Compliance on  Cisco Catalyst Center
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILE_PATH }}"

  vars:
    state: merged
    catalyst_center_login: &catalyst_center_login
      dnac_host: "{{ catalyst_center_host | default(dnac_host) }}"
      dnac_username: "{{ catalyst_center_username | default(dnac_username) }}"
      dnac_password: "{{ catalyst_center_password | default(dnac_password) }}"
      dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
      dnac_port: "{{ catalyst_center_port | default(443) }}"
      dnac_verify: "{{ catalyst_center_verify | default(dnac_verify) }}"
      config_verify: "{{ catalyst_center_config_verify | default(False) }}"
      dnac_debug: "{{ catalyst_center_debug | default(False) }}"
      dnac_log: "{{ catalyst_center_log | default(False) }}"
      dnac_log_level: "{{ catalyst_center_log_level | default('INFO') }}"
      dnac_log_file_path: "{{ catalyst_center_log_file_path |  default(omit) }}"
      dnac_log_append: "{{ catalyst_center_log_append |  default(False) }}"
      dnac_api_task_timeout: "{{ catalyst_center_api_task_timeout |  default(1200) }}"
      
  tasks:
    - name: Network Compliance devices on Cisco Catalyst Center
      set_fact:
        long_op_start: "{{ now() }}"
    - name: Network Compliance devices on Cisco Catalyst Center
      cisco.dnac.network_compliance_workflow_manager:
        <<: *catalyst_center_login
        state: merged
        config: "{{network_compliance_details}}"
      register: network_compliance_output
      when: network_compliance_details is defined
    - name: Print the Network Compliance devices output
      debug:
        msg: "{{network_compliance_output}}"
    - name: Network Compliance devices playbook end time
      set_fact:
        long_op_end: "{{ now() }}"
    - name: Print Network Compliance devices playbook execution time
      debug:
        msg: "Network Compliance devices playbook run time: {{ long_op_start }}, end: {{ long_op_end }}"
  post_tasks:
    - name: run command module to find python version
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local
