---
#the following playbook is used to run compliance, fix config compliance, on Cisco Catalyst Center
# The playbook is executed with the following command
# ansible-playbook -i inventory/hosts.yml network_compliance_playbook.yml --extra-vars "VARS_FILES_PATH=../vars/network_compliance_inputs.yml"
- name: Network Compliance on  Cisco Catalyst Center
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILE_PATH }}"

  vars:
    state: merged
    dnac_login: &dnac_login
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ dnac_username }}"
      dnac_password: "{{ dnac_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ catalyst_center_version  | default(dnac_version) }}"
      dnac_debug: "{{ dnac_debug }}"
      dnac_log: "{{ dnac_log }}"
      dnac_log_level: "{{ dnac_log_level }}"
  tasks:
    - name: Network Compliance devices on Cisco Catalyst Center
      set_fact:
        long_op_start: "{{ now() }}"
    - name: Network Compliance devices on Cisco Catalyst Center
      cisco.dnac.network_compliance_workflow_manager:
        <<: *dnac_login
        state: merged
        config: "{{network_compliance_details}}"
      register: network_compliance_output
      when: network_compliance_details is defined
    - name: Print the Network Compliance devices output
      debug:
        msg: "{{network_compliance_output}}"
    - name: Network Compliance devices playbook end time
      set_fact:
        long_op_end: "{{ now() }}"
    - name: Print Network Compliance devices playbook execution time
      debug:
        msg: "Network Compliance devices playbook run time: {{ long_op_start }}, end: {{ long_op_end }}"
  post_tasks:
    - name: run command module to find python version
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local
