---
  - name: DEBUG all_network_devices
    ansible.builtin.debug:
      msg: "{{ all_network_devices }}"
      
  - name: DEBUG filters_object
    ansible.builtin.debug:
      msg: "{{ filters_object }}"

  - name: Get devices Serial Numbers for a given site dict filters_object
    set_fact:
      filtered_devices_list1:  "{{ all_network_devices | selectattr('site', 'equalto', filters_object.siteName) | map(attribute='serialNumber') | list }} "
    when: all_network_devices is defined and filters_object is defined and filters_object.siteName is defined and filters_object.siteName != ""

  - name: DEBUG filtered_devices_list1
    ansible.builtin.debug:
      msg: "{{ filtered_devices_list1 }}"
    when: filtered_devices_list1 is defined

  - name: Get devices Serial Numbers for a given role dict filters_object
    set_fact:
      filtered_devices_list2:  "{{ all_network_devices | selectattr('role', 'equalto', filters_object.deviceRole) | map(attribute='serialNumber') | list }} "
    when: all_network_devices is defined and filters_object is defined and filters_object.deviceRole is defined and filters_object.deviceRole != ""

  - name: DEBUG filtered_devices_list2
    ansible.builtin.debug:
      msg: "{{ filtered_devices_list2 }}"
    when: filtered_devices_list2 is defined

  - name: Get devices Serial Numbers for a given deviec type name
    set_fact:
      filtered_devices_list3:  "{{ all_network_devices | selectattr('type', 'equalto', filters_object.deviceFamilyName) | map(attribute='serialNumber') | list }} "
    when: all_network_devices is defined and filters_object is defined and filters_object.deviceFamilyName is defined and filters_object.deviceFamilyName != ""

  - name: DEBUG filtered_devices_list3
    ansible.builtin.debug:
      msg: "{{ filtered_devices_list3 }}"
    when: filtered_devices_list3 is defined

  - name: Get devices Serial Numbers for a given deviec family name switches and Hub, wireless controllers
    set_fact:
      filtered_devices_list4:  "{{ all_network_devices | selectattr('family', 'equalto', filters_object.family) | map(attribute='serialNumber') | list }} "
    when: all_network_devices is defined and filters_object is defined and filters_object.family is defined and filters_object.family != ""

  - name: DEBUG filtered_devices_list4
    ansible.builtin.debug:
      msg: "{{ filtered_devices_list4 }}"
    when: filtered_devices_list4 is defined

  - name: Get devices Serial Numbers which are present in both filtered_devices_list1, filtered_devices_list2, filtered_devices_list3, filtered_devices_list4
    set_fact:
      filtered_devices_list: "{{ filtered_devices_list1 | intersect(filtered_devices_list2) | intersect(filtered_devices_list3) | intersect(filtered_devices_list4) }}"
    when: filtered_devices_list1 is defined and filtered_devices_list2 is defined and filtered_devices_list3 is defined and filtered_devices_list4 is defined
  - name: Get devices Serial Numbers which are present in both filtered_devices_list1, filtered_devices_list2, filtered_devices_list3
    set_fact:
      filtered_devices_list: "{{ filtered_devices_list1 | intersect(filtered_devices_list2) | intersect(filtered_devices_list3) }}"
    when: filtered_devices_list1 is defined and filtered_devices_list2 is defined and filtered_devices_list3 is defined and filtered_devices_list4 is not defined
  - name: Get devices Serial Numbers which are present in both filtered_devices_list1, filtered_devices_list2, filtered_devices_list4
    set_fact:
      filtered_devices_list: "{{ filtered_devices_list1 | intersect(filtered_devices_list2) | intersect(filtered_devices_list4) }}"
    when: filtered_devices_list1 is defined and filtered_devices_list2 is defined and filtered_devices_list3 is not defined and filtered_devices_list4 is defined
  - name: Get devices Serial Numbers which are present in both filtered_devices_list1, filtered_devices_list3, filtered_devices_list4
    set_fact:
      filtered_devices_list: "{{ filtered_devices_list1 | intersect(filtered_devices_list3) | intersect(filtered_devices_list4) }}"
    when: filtered_devices_list1 is defined and filtered_devices_list2 is not defined and filtered_devices_list3 is defined and filtered_devices_list4 is defined
  - name: Get devices Serial Numbers which are present in both filtered_devices_list2, filtered_devices_list3, filtered_devices_list4
    set_fact:
      filtered_devices_list: "{{ filtered_devices_list2 | intersect(filtered_devices_list3) | intersect(filtered_devices_list4) }}"
    when: filtered_devices_list1 is not defined and filtered_devices_list2 is defined and filtered_devices_list3 is defined and filtered_devices_list4 is defined
  - name: Get devices Serial Numbers which are present in both filtered_devices_list1, filtered_devices_list2
    set_fact:
      filtered_devices_list: "{{ filtered_devices_list1 | intersect(filtered_devices_list2) }}"
    when: filtered_devices_list1 is defined and filtered_devices_list2 is defined and filtered_devices_list3 is not defined and filtered_devices_list4 is not defined
  - name: Get devices Serial Numbers which are present in both filtered_devices_list1, filtered_devices_list3
    set_fact:
      filtered_devices_list: "{{ filtered_devices_list1 | intersect(filtered_devices_list3) }}"
    when: filtered_devices_list1 is defined and filtered_devices_list2 is not defined and filtered_devices_list3 is defined and filtered_devices_list4 is not defined
  - name: Get devices Serial Numbers which are present in both filtered_devices_list1, filtered_devices_list4
    set_fact:
      filtered_devices_list: "{{ filtered_devices_list1 | intersect(filtered_devices_list4) }}"
    when: filtered_devices_list1 is defined and filtered_devices_list2 is not defined and filtered_devices_list3 is not defined and filtered_devices_list4 is defined
  - name: Get devices Serial Numbers which are present in both filtered_devices_list2, filtered_devices_list3
    set_fact:
      filtered_devices_list: "{{ filtered_devices_list2 | intersect(filtered_devices_list3) }}"
    when: filtered_devices_list1 is not defined and filtered_devices_list2 is defined and filtered_devices_list3 is defined and filtered_devices_list4 is not defined
  - name: Get devices Serial Numbers which are present in both filtered_devices_list2, filtered_devices_list4
    set_fact:
      filtered_devices_list: "{{ filtered_devices_list2 | intersect(filtered_devices_list4) }}"
    when: filtered_devices_list1 is not defined and filtered_devices_list2 is defined and filtered_devices_list3 is not defined and filtered_devices_list4 is defined
  - name: Get devices Serial Numbers which are present in both filtered_devices_list3, filtered_devices_list4
    set_fact:
      filtered_devices_list: "{{ filtered_devices_list3 | intersect(filtered_devices_list4) }}"
    when: filtered_devices_list1 is not defined and filtered_devices_list2 is not defined and filtered_devices_list3 is defined and filtered_devices_list4 is defined

  - name: Get the device list when only filtered_devices_list1 is defined
    set_fact:
      filtered_devices_list: "{{ filtered_devices_list1 }}"
    when: filters_object is defined and filters_object.siteName is defined and filters_object.deviceRole is not defined and filters_object.deviceFamilyName is not defined and filters_object.family is not defined and filtered_devices_list1 is defined
  - name: Get the device list when only filtered_devices_list2 is defined
    set_fact:
      filtered_devices_list: "{{ filtered_devices_list2 }}"
    when: filters_object is defined and filters_object.siteName is not defined and filters_object.deviceRole is defined and filters_object.deviceFamilyName is not defined and filters_object.family is not defined and filtered_devices_list2 is defined

  - name: Get the device list when only filtered_devices_list3 is defined
    set_fact:
      filtered_devices_list: "{{ filtered_devices_list3 }}"
    when: filters_object is defined and filters_object.siteName is not defined and filters_object.deviceRole is not defined and filters_object.deviceFamilyName is defined and filters_object.family is not defined and filtered_devices_list3 is defined

  - name: Get the device list when only filtered_devices_list4 is defined
    set_fact:
      filtered_devices_list: "{{ filtered_devices_list4 }}"
    when: filters_object is defined and filters_object.siteName is not defined and filters_object.deviceRole is not defined and filters_object.deviceFamilyName is not defined and filters_object.family is defined and filtered_devices_list4 is defined

  - name: DEBUG filtered_devices_list
    ansible.builtin.debug:
      msg: "{{ filtered_devices_list }}"
    when: filtered_devices_list is defined