---
# tasks file for discovery

- name: Includes Discovery info
  include_vars:
    file: "{{ discovery_input_file }}"
    name: vars_map
  tags: always

- name: Discovery Multi IP Address Ranges
  cisco.dnac.discovery_workflow_manager:
    dnac_host: "{{ dnac_host }}"
    dnac_username: "{{ dnac_username }}"
    dnac_password: "{{ dnac_password }}"
    dnac_verify: "{{ dnac_verify }}"
    dnac_port: "{{ dnac_port }}"
    dnac_version: "{{ dnac_version }}"
    dnac_debug: "{{ dnac_debug }}"
    dnac_log: "{{ dnac_log }}"
    dnac_log_level: "{{ dnac_log_level }}"
    config_verify: True
    state: merged
    config:
      - "{{ item }}"
  loop: "{{ vars_map.multi_range }}"
  tags: create_discovery
